name: Check PR title
description: Check PR title
inputs:
  token:
    description: "Github token"
    required: true
branding:
  icon: git-pull-request
  color: purple
runs:
  using: composite
  steps:
    - uses: amannn/action-semantic-pull-request@v5
      with:
        types: |
          feat
          fix
          docs
          style
          refactor
          perf
          test
          build
          ci
          chore
          revert
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
