name: ftrack Sync
description: "Sync PR status with ftrack tasks provided in PR descriptions"
inputs:
  action:
    description: "Check package.json for available scripts, e.g. check-pr or release-notes"
  ftrackUrl:
    description: "URL to the ftrack instance"
    required: true
  ftrackApiKey:
    description: "API key to the ftrack instance"
    required: true
  ftrackLoginEmail:
    description: "The ftrack user email to log in with using the corresponding API key"
    required: true
  ftrackUserId:
    description: "The user ID to post notes as"
    required: true
  token:
    description: "The GitHub token to use for authentication"
    required: true
  context:
    required: false
    description: "Additional context required for actions in JSON format"
runs:
  using: "composite"
  steps:
    - name: Set up Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - shell: bash
      working-directory: ${{ github.action_path }}
      run: bun install --production --frozen-lockfile
    - uses: 8BitJonny/gh-get-current-pr@3.0.0
      id: PR
      with:
        sha: ${{ github.event.pull_request.head.sha }}
    - name: bun run ${{ inputs.action }}
      working-directory: ${{ github.action_path }}
      shell: bash
      run: bun run ${{ inputs.action }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        FTRACK_API_KEY: ${{ inputs.ftrackApiKey }}
        FTRACK_URL: ${{ inputs.ftrackUrl }}
        FTRACK_LOGIN_EMAIL: ${{ inputs.ftrackLoginEmail }}
        FTRACK_USER_ID: ${{ inputs.ftrackUserId }}
        PR_PAYLOAD: ${{ steps.PR.outputs.pr }}
        GITHUB_PAYLOAD: ${{ toJson(github) }}
        CONTEXT: ${{ inputs.context }}
