name: Deployment

on:
  deployment:

jobs:
  check-pr:
    timeout-minutes: 5
    name: Check PR & Sync
    runs-on: ubuntu-latest
    steps:
      - name: "Dump GitHub context"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
