name: PR

on:
  workflow_call:
    secrets:
      ftrackApiKey:
        description: "The API key to the ftrack instance"
        required: false
      token:
        description: "The GitHub token"
        required: false
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check-pr:
    name: Basic PR Checks & Sync
    runs-on: ubuntu-latest
    steps:
      # required so we can reference the actions locally
      - name: Checkout workflows repo
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.workflows-ref }}
          path: workflows
          repository: ftrackhq/ftrack-actions
          token: ${{ secrets.token }}
      - name: ftrack Sync
        uses: ./workflows/actions/ftrack-sync
        with:
          ftrackUrl: https://dev.ftrackapp.com
          ftrackLoginEmail: "github_bot@ftrack.com"
          ftrackUserId: "76a40852-359d-11ed-8012-aab5768efa1e"
          ftrackApiKey: ${{ secrets.ftrackApiKey || secrets.FTRACK_API_KEY }}
      - name: Check PR Title
        uses: ./workflows/actions/check-pr-title
        with:
          token: ${{ secrets.token || secrets.GITHUB_TOKEN }}
