name: CD

on:
  workflow_call:
    secrets:
      token:
        description: "The GitHub token"
        required: true
      gcrJsonKey:
        description: "JSON key for GCR authentication"
        required: true
      dockerSecrets:
        description: "Docker build push action"
        required: false
    inputs:
      gcrRegistry:
        type: string
        description: "Google Cloud Registry URL"
        required: true
      ghcrRegistry:
        type: string
        description: "GitHub Registry URL"
        required: true
      gcrNamespace:
        type: string
        description: "Image prefix when uploading to Google Cloud Registry"
        required: true
      ghcrNamespace:
        type: string
        description: "Image prefix when uploading to GitHub Registry"
        required: true
      dockerFile:
        type: string
        description: Path to the Dockerfile. (default ./Dockerfile)
        required: false
        default: ./Dockerfile
      context:
        type: string
        description: Path to context
        required: false
        default: .
      lint:
        type: boolean
        description: "Set to true to lint Dockerfile as part of build"
        required: false
        default: false
      imageName:
        type: string
        description: "Name of Docker image"
        required: true
      target:
        type: string
        description: "Sets the target stage to build"
        required: false
        default: ""
      provenance:
        type: string
        description: Generate provenance attestation for the build (shorthand for --attest=type=provenance). Currently not working with gcr
        required: false
        default: ""
      dockerBuildArgs:
        type: string
        required: false
        default: ""
      additionalImages:
        type: string
        required: false
        default: ""

jobs:
  build-and-push-image:
    timeout-minutes: ${{ fromJSON(vars.DEFAULT_JOB_TIMEOUT) }}
    name: "Build and push to registries"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # required so we can reference the actions locally
      - name: Checkout workflows repo
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.workflows-ref }}
          path: workflows
          repository: ftrackhq/ftrack-actions
          token: ${{ secrets.token || secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.ghcrRegistry }}
          username: ${{ github.actor }}
          password: ${{ secrets.token }}

      - name: Log in to the Google Cloud Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.gcrRegistry }}
          username: _json_key
          password: ${{ secrets.gcrJsonKey }}

      - name: Build and publish
        uses: ./workflows/actions/publish-docker
        with:
          token: ${{ secrets.token || secrets.GITHUB_TOKEN }}
          dockerFile: ${{ inputs.dockerFile }}
          context: ${{ inputs.context }}
          lint: ${{ inputs.lint }}
          imageName: ${{ inputs.imageName }}
          target: ${{ inputs.target }}
          provenance: ${{ inputs.provenance }}
          dockerBuildArgs: ${{ inputs.dockerBuildArgs }}
          dockerSecrets: ${{ secrets.dockerSecrets }}
          images: |
            ${{ inputs.gcrRegistry }}/${{ inputs.gcrNamespace }}/${{ inputs.imageName }}
            ${{ inputs.ghcrRegistry }}/${{ inputs.ghcrNamespace }}/${{ inputs.imageName }}
            ${{ inputs.additionalImages }}
