name: JS

on:
  workflow_call:
  push:

env:
  TZ: UTC

jobs:
  test-js:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js from .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version: 20.4.0

      # caching with actions/setup-node isn't supported with yarn 3
      # so we use this workaround https://github.com/actions/setup-node/issues/488
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
        shell: bash
      - name: Restore yarn cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-cache-folder-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
          restore-keys: |
            yarn-cache-folder-

      - run: yarn install --immutable
      # Only run `yarn build` if present.
      # Really wish we had `npm run --if-present` available for yarn
      - run: if (yarn run | grep "\sbuild"); then yarn build; else true; fi
      - run: yarn test
