name: JS

on:
  push:

env:
  TZ: UTC

jobs:
  test-js:
    timeout-minutes: ${{ fromJSON(vars.DEFAULT_JOB_TIMEOUT) }}
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: cd actions/ftrack-sync && bun install && bun run test
      - name: ftrack Sync
        uses: ./workflows/actions/ftrack-sync
        with:
          action: "release-notes"
          ftrackUrl: https://dev.ftrackapp.com
          ftrackLoginEmail: "github_bot@backlight.co"
          ftrackUserId: "76a40852-359d-11ed-8012-aab5768efa1e"
          ftrackApiKey: ${{ secrets.ftrackApiKey || secrets.FTRACK_API_KEY }}
          token: ${{ secrets.token || secrets.GITHUB_TOKEN }}
