name: JS

on:
  push:

env:
  TZ: UTC

jobs:
  test-js:
    timeout-minutes: ${{ fromJSON(vars.DEFAULT_JOB_TIMEOUT) }}
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: cd actions/ftrack-sync && bun install && bun run test
