name: Release notes

on:
  release:
    types:
      - released

  workflow_call:
    inputs:
      zendeskUsername:
        type: string
        description: "The Zendesk username"
        required: true
    secrets:
      ftrackApiKey:
        description: "The API key to the ftrack instance"
        required: true
      token:
        description: "The GitHub token"
        required: true
      zendeskApiKey:
        description: "Slack token"
        required: true

jobs:
  zendesk:
    name: Update release notes in Zendesk
    runs-on: ubuntu-latest
    steps:
      # To check the github context
      - name: Dump Github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      # required so we can reference the actions locally
      - name: Checkout workflows repo
        uses: actions/checkout@v3
        with:
          # you can set this to your branch when modifying actions and want too assert that it works
          # ref: backlog/generate-release-notes-automatically-from-fields-in-ftrack
          path: workflows
          repository: ftrackhq/ftrack-actions
          token: ${{ secrets.token || secrets.GITHUB_TOKEN }}
      - name: ftrack Sync
        uses: ./workflows/actions/ftrack-sync
        with:
          action: "release-notes"
          ftrackUrl: https://dev.ftrackapp.com
          ftrackLoginEmail: "github_bot@backlight.co"
          ftrackUserId: "76a40852-359d-11ed-8012-aab5768efa1e"
          ftrackApiKey: ${{ secrets.ftrackApiKey || secrets.FTRACK_API_KEY }}
          zendeskApiKey: ${{ secrets.zendeskApiKey || secrets.ZENDESK_API_KEY }}
          zendeskUsername: ${{ inputs.zendeskUsername }}
          token: ${{ secrets.token || secrets.GITHUB_TOKEN }}
