name: Release notes

on:
  release:
    types:
      - released

  workflow_call:
    secrets:
      ftrackApiKey:
        description: "The API key to the ftrack instance"
        required: true
      token:
        description: "The GitHub token"
        required: true

jobs:
  sync-release:
    timeout-minutes: 5
    name: Sync release in ftrack
    runs-on: ubuntu-latest
    steps:
      # required so we can reference the actions locally
      - name: Checkout workflows repo
        uses: actions/checkout@v3
        with:
          # you can set this to your branch when modifying actions and want too assert that it works
          # ref: update-tasks-with-release-tag
          path: workflows
          repository: ftrackhq/ftrack-actions
          token: ${{ secrets.token || secrets.GITHUB_TOKEN }}
      - name: ftrack Sync
        uses: ./workflows/actions/ftrack-sync
        with:
          action: "release-notes"
          ftrackUrl: https://dev.ftrackapp.com
          ftrackLoginEmail: "github_bot@backlight.co"
          ftrackUserId: "76a40852-359d-11ed-8012-aab5768efa1e"
          ftrackApiKey: ${{ secrets.ftrackApiKey || secrets.FTRACK_API_KEY }}
          token: ${{ secrets.token || secrets.GITHUB_TOKEN }}
